create database SurucuKursuDB;

CREATE TABLE Ogrenci 
(OgrenciID INT PRIMARY KEY IDENTITY(1,1),
 Ad NVARCHAR(50) NOT NULL,
 Soyad NVARCHAR(50) NOT NULL,
 TCNo CHAR(11) NOT NULL UNIQUE ,
 Telefon NVARCHAR(20) NULL,
 KayitTarihi DATETIME NOT NULL DEFAULT GETDATE());

CREATE TABLE Egitmen 
(EgitmenID INT PRIMARY KEY IDENTITY(1,1),
 Ad NVARCHAR(50) NOT NULL,
 Soyad NVARCHAR(50) NOT NULL,
 Brans NVARCHAR(50) NOT NULL,
 Telefon NVARCHAR(20) NULL);
 

CREATE TABLE Ders 
(DersID INT PRIMARY KEY IDENTITY(1,1),
 DersAdi NVARCHAR(100),
 DersTuru NVARCHAR(50), 
 EgitmenID INT FOREIGN KEY REFERENCES Egitmen(EgitmenID) ON DELETE CASCADE ON UPDATE CASCADE);
 
 CREATE TABLE OgrenciDers 
(OgrenciID INT NOT NULL FOREIGN KEY REFERENCES Ogrenci(OgrenciID) ON DELETE CASCADE ON UPDATE CASCADE,     
 DersID INT NOT NULL FOREIGN KEY REFERENCES Ders(DersID) ON DELETE CASCADE ON UPDATE CASCADE,
 KatilimTarihi DATETIME NOT NULL DEFAULT GETDATE(),       
 PRIMARY KEY (OgrenciID, DersID));      
 

CREATE TABLE Odeme 
(OdemeID INT PRIMARY KEY IDENTITY(1,1),
 OgrenciID INT NOT NULL FOREIGN KEY REFERENCES Ogrenci(OgrenciID) ON DELETE CASCADE ON UPDATE CASCADE, 
 Tutar DECIMAL(10,2) NOT NULL,
 OdemeTarihi DATETIME NOT NULL DEFAULT GETDATE(),
 Aciklama NVARCHAR(200));
 

CREATE TABLE Sinav 
(SinavID INT PRIMARY KEY IDENTITY(1,1),
 OgrenciID INT NOT NULL FOREIGN KEY REFERENCES Ogrenci(OgrenciID) ON DELETE CASCADE ON UPDATE CASCADE,
 SinavTuru NVARCHAR(50) NOT NULL,        
 SinavTarihi DATETIME NOT NULL DEFAULT GETDATE(),
 Sonuc NVARCHAR(20) NOT NULL);    
 

CREATE TABLE Arac 
(AracID INT PRIMARY KEY IDENTITY(1,1),
 Plaka NVARCHAR(20) NOT NULL UNIQUE,
 Marka NVARCHAR(50) NOT NULL,
 Model NVARCHAR(50) NOT NULL,
 KullanilanDersID INT FOREIGN KEY REFERENCES Ders(DersID) ON DELETE SET NULL ON UPDATE CASCADE);
        

    

    
    
